# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 161e385a5b698a8fc4a4f544a9b6b17d75bfe54141f9c10adedf0ce2522f2bd452c8fccc39f875abf94f15fb861f53e5b716aeead4f6a25a4d021e3d53f57848

test:
  secret_key_base: 274d4811a3021ac4a09509be75bce52cf9483e1f3a3219a2dcfebd2104f9b48b581d2c3f9146279487da77197a054b2005a1d112568a53a3339eb98af8fd438c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
